Repository wecode-bootcamp-korea/14-1st-Trendi-frontend, pull requests merged in 2020-11, with the labels that each got.

#1 [장재원] Add : Signup agreement 기능구현 및 스타일링
  README.md
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/SignUp/Agreement.js
  src/Pages/SignUp/Agreement.scss
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
  src/Pages/SignUp/StatusView.js
  src/Pages/SignUp/StatusView.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#2 [신세원]Add: Brandi Nav바 구현중
  README.md
  package-lock.json
  package.json
  public/images/banner.png
  public/images/picture1.jpg
  public/images/picture2.jpg
  public/images/picture3.jpg
  public/images/picture4.jpg
  public/images/picture5.jpg
  public/images/trandi.jpg
  public/index.html
  src/Components/Footer/Footer.js
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/ShoppingNav.js
  src/Components/Nav/ShoppingNav.scss
  src/Components/Nav/Test.js
  src/Pages/Main/Main.js
  src/Pages/Main/SimpleSlider.js
  src/Pages/Main/SimpleSlider.scss
  src/Pages/Main/Slider.js
  src/Routes.js
  src/common.scss
  src/index.js
Labels: Status: 리뷰 요청

#3 [신세원]Add: Brandi Footer 레이아웃 및 CSS 구현완료
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Pages/Main/Main.js
  src/Routes.js
Labels: Status: 수정 요청, Status: 컨플릭트 해결 완료

#10 [신세원 Feature/footer 레이아웃 수정완료
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Pages/Main/Main.js
  src/Routes.js
Labels: Status: Accepted

#12 [신세원]Feature/nav 레이아웃 센터 수정작업 완료
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/ShoppingNav.js
  src/Components/Nav/ShoppingNav.scss
  src/Pages/Main/SimpleSlider.js
  src/Pages/Main/SimpleSlider.scss
  src/Routes.js
Labels: Status: Accepted

#6 [장재원] Add : 마이페이지 레이아웃 완성
  src/Components/Nav/Nav.scss
  src/Pages/Main/Main.scss
  src/Pages/MyPage/MyPage.js
  src/Pages/MyPage/MyPage.scss
Labels: 리뷰 진행 중

#8 [장재원]ADD : 회원가입 완료 레이아웃 완료
  public/images/signup_complete.png
  src/Pages/SignUp/Agreement.js
  src/Pages/SignUp/Agreement.scss
  src/Pages/SignUp/Complete.js
  src/Pages/SignUp/Complete.scss
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
  src/Pages/SignUp/StatusView.js
  src/Pages/SignUp/StatusView.scss
  src/Routes.js
Labels: Status: 컨플릭트 해결 완료

#5 [장재원]Add : SigupInfo 기능 및 레이아웃 완료
  public/images/lock.png
  src/Pages/SignUp/Agreement.js
  src/Pages/SignUp/Agreement.scss
  src/Pages/SignUp/SignUpInfo.js
  src/Pages/SignUp/SignUpInfo.scss
  src/Pages/SignUp/StatusView.js
  src/Routes.js
  src/config.json
  src/reset.scss
Labels: Status: 컨플릭트 해결 완료

#7 [신세원 Feature/detail_item 컴포넌트 레이아웃 구현완료
  package-lock.json
  package.json
  public/images/cart.png
  public/images/close.png
  public/images/clothes1.png
  public/images/clothes2.png
  public/images/clothes3.png
  public/images/clothes4.png
  public/images/clothes5.png
  public/images/heart.png
  public/images/home.png
  public/images/naver.png
  public/images/star.png
  src/Components/DetailItem/DetailItem.js
  src/Components/DetailItem/DetailItem.scss
  src/Components/DetailItem/DropDownBox.js
  src/Components/DetailItem/DropDownBox.scss
  src/Components/DetailItem/ITEM.js
  src/Components/DetailItem/ItemSection.js
  src/Components/DetailItem/ItemSection.scss
  src/Components/DetailItem/OrderBox.js
  src/Components/DetailItem/OrderBox.scss
  src/Components/DetailItem/PictureBox.js
  src/Components/DetailItem/PictureBox.scss
  src/Components/DetailItem/STAR.js
  src/Pages/Main/ItemList.js
  src/Pages/Main/Main.js
  src/Routes.js
  src/common.scss
  src/index.js
  src/reset.scss
Labels: Status: 컨플릭트 해결 완료

#9 [장재원] ADD : 상품 detail page ui 완성 및 서버 연동 준비 완료
  package-lock.json
  package.json
  public/data/MOCK_DATA.json
  src/Components/DetailItem/Review.js
  src/Components/DetailItem/Review.scss
  src/Components/DetailItem/ReviewListComponet.js
  src/Components/DetailItem/ReviewListComponet.scss
  src/Components/DetailItem/WriteReview.js
  src/Components/DetailItem/WriteReview.scss
  src/Routes.js
  src/config.json
Labels: Status: 컨플릭트 해결 완료

#11 [장재원] ADD : 로그인 창 기능 구현 및 서버 테스트
  package-lock.json
  package.json
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Main/Main.js
  src/Pages/Main/SimpleSlider.js
Labels: Status: 컨플릭트 해결 완료

#13 [신세원] Feature/item list 레이아웃 및 기능 구현중
  package-lock.json
  public/data/MOCK_DATA.json
  public/images/down.png
  public/images/haru2.png
  public/images/p3.jpg
  public/images/up.png
  src/Components/Footer/Footer.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/ShoppingNav.js
  src/Components/Nav/ShoppingNav.scss
  src/Pages/CategoryPage/CATEGORY.js
  src/Pages/CategoryPage/CategoryPage.js
  src/Pages/CategoryPage/CategoryPage.scss
  src/Pages/CategoryPage/ItemCategory.js
  src/Pages/CategoryPage/ItemCategory.scss
  src/Pages/CategoryPage/ShirtList.js
  src/Pages/CategoryPage/ShirtList.scss
  src/Pages/Main/Main.js
  src/Pages/Main/SimpleSlider.scss
  src/Pages/SignUp/StatusView.js
  src/Routes.js
  src/common.scss
  src/config.json
Labels: Status: 리뷰 요청

#14 [신세원] Feature/detail item item infomation bar 스크롤 기능구현
  src/Components/DetailItem/DetailItem.js
  src/Components/DetailItem/DetailItem.scss
  src/Components/DetailItem/DropDownBox.js
  src/Components/DetailItem/ItemSection.js
  src/Components/DetailItem/ItemSection.scss
  src/Components/DetailItem/OrderBox.js
  src/Components/DetailItem/PictureBox.js
  src/Components/DetailItem/STAR.js
  src/Components/ItemInfomationBar/ItemInfo.js
  src/Components/ItemInfomationBar/ItemInfo.scss
  src/Components/ItemInfomationBar/ItemInfomationBar.js
  src/Components/ItemInfomationBar/ItemInfomationBar.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Slider/SimpleSlider.js
  src/Components/Slider/SimpleSlider.scss
  src/Pages/CategoriePage/ItemCategory.scss
  src/Pages/SignUp/StatusView.js
  src/config.json
Labels: Status: 컨플릭트 해결 완료

#15 [신세원] main 브랜치 레이아웃 및 기본 구성 세팅 완료
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
Labels: Status: 컨플릭트 해결 요청

#16 [신세원]Feature/nav바 동적 라우터 기능 구현중
  src/Components/DetailItem/WriteReview.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/Test.js
Labels: Status: 컨플릭트 해결 완료

#21 [신세원]Feature/detail item item infomation bar 기능 구현 마무리 작업
  package-lock.json
  src/Components/DetailItem/DetailItem.js
  src/Components/DetailItem/DetailItem.scss
  src/Components/DetailItem/Review.js
  src/Components/DetailItem/Review.scss
  src/Components/ItemInfomationBar/ItemInfo.js
  src/Components/ItemInfomationBar/ItemInfo.scss
  src/Components/ItemInfomationBar/ItemInfomationBar.js
  src/Components/Nav/Nav.js
  src/Pages/CategoryPage/CategoryPage.js
  src/Pages/CategoryPage/ItemCategory.js
  src/Pages/CategoryPage/ShirtList.js
  src/config.json
Labels: Status: 리뷰 요청

#17 [장재원]ADD : Feature/my cart 기능 및 ui 구현 완료
  public/data/MOCK_DATA2.json
  public/images/delivery.png
  public/images/trash.png
  src/Pages/MyCart/MyCart.js
  src/Pages/MyCart/MyCart.scss
  src/Pages/MyCart/SelleProduct.js
  src/Pages/MyCart/SellerProduct.scss
  src/Routes.js
  src/config.json
Labels: Status: 리뷰 요청

#22 [장재원]UPDATE : Feature/login in page 로그인 기능 구현
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/ShoppingNav.scss
  src/Pages/Login/Login.js
  src/Pages/Main/Main.js
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUpInfo.js
  src/Routes.js
  src/config.json
Labels: Status: 컨플릭트 해결 완료, 리뷰 진행 중

#23 [신세원][feature/detail_item_infomationbar] 최종 마무리 단계
  public/images/apple.png
  public/images/facebook.png
  public/images/google.png
  src/Components/DetailItem/DetailItem.js
  src/Components/DetailItem/DetailItem.scss
  src/Components/DetailItem/DropDownBox.js
  src/Components/DetailItem/Review.js
  src/Components/DetailItem/ReviewListComponet.js
  src/Components/DetailItem/WriteReview.scss
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/ShoppingNav.js
  src/Components/Nav/ShoppingNav.scss
  src/Pages/CategoriePage/ItemCategory.scss
  src/Pages/CategoryPage/CategoryPage.js
  src/Pages/CategoryPage/ShirtList.js
  src/Pages/CategoryPage/ShirtList.scss
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Main/ItemList.js
  src/Pages/Main/ItemList.scss
  src/Pages/Main/Main.js
  src/Pages/Main/SimpleSlider.js
  src/Pages/MyCart/MyCart.js
  src/Pages/MyCart/SelleProduct.js
  src/Pages/SignUp/SignUpInfo.js
  src/Routes.js
  src/common 2.scss
  src/common 3.scss
  src/common 4.scss
  src/common 5.scss
  src/common 6.scss
  src/config.json
Labels: Status: 컨플릭트 해결 요청
